apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: nginx-ingress
  name: default-http-backend
  labels:
    app: default-http-backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: default-http-backend
    spec:
      containers:
        - name: default-http-backend
          image: gcr.io/benzen-179605/default-http-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          env:
          - name: APP_VERSION
            value: "VER_3"
