services:
  - docker:dind

stages:
  - build
  - deploy

build:
  stage: build
  image: docker:dind
  script: |
    env
    pwd
    ls
    docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    docker pull $CI_REGISTRY_IMAGE:lastest || true
    docker build --cache-from $CI_REGISTRY_IMAGE:lastest -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA .
    docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE:latest
    docker push $CI_REGISTRY_IMAGE:latest
  only:
    - master

deploy:
  image: google/cloud-sdk
  stage: deploy
  script: |
    kubectl apply -f .k8s-deploy.yml
  only:
    - master
