services:
  - docker:dind

stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2

build:
  stage: build
  image: docker:dind
  script: |
    mkdir -p $CI_PROJECT_DIR/cache/
    docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    docker load -i $CI_PROJECT_DIR/images/latest.tar || docker pull $CI_REGISTRY_IMAGE:lastest || true
    docker build --cache-from $CI_REGISTRY_IMAGE:lastest -t $CI_REGISTRY_IMAGE:lastest .
    docker push $CI_REGISTRY_IMAGE:lastest
  only:
    - master

deploy:
  image: google/cloud-sdk
  stage: deploy
  script: |
    kubectl apply -f .k8s-deploy.yml
  only:
    - master
