services:
  - docker:dind

stages:
  - build
  - deploy

build:
  stage: build
  image: docker
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker pull "$CI_REGISTRY_IMAGE:latest"
    - docker build --cache-from "$CI_REGISTRY_IMAGE:latest" -t "$CI_REGISTRY_IMAGE:latest" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master

deploy:
  image: google/cloud-sdk
  stage: deploy
  script:
    - kubectl apply -f .k8s-deploy.yml
  only:
    - master
