services:
  - docker:dind

stages:
  - build
  - deploy

build:
  stage: build
  image: docker
  script:
    - docker pull $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME
    - docker build --cache-from $CI_REGISTRY_IMAGE:CI_BUILD_REF_NAME -t $CI_REGISTRY_IMAGE:CI_BUILD_REF .
    - docker push $CI_REGISTRY_IMAGE:$CI_BUILD_REF
  only:
    - master

deploy:
  image: google/cloud-sdk
  stage: deploy
  script:
    - kubectl apply -f .k8s-deploy.yml
  only:
    - master
