apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: nginx-ingress
  name: default-http-backend
  labels:
    app: default-http-backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: default-http-backend
    spec:
      imagePullSecrets:
        - name: gitlab-registry-secret
      containers:
        - name: default-http-backend
          image: registry.benzen.io/services/default-http-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          env:
          - name: DEPLOYED_AT
            value: "DEPLOYED_AT_VAL"
