apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  name: default-http-backend
  labels:
    app: default-http-backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: default-http-backend
    spec:
      containers:
        - name: default-http-backend
          image: registry.benzen.io/services/default-http-backend
          ports:
            - containerPort: 8000
              name: http
          # resources:
          #   requests:
          #     cpu: 10m
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: default-http-backend
  name: default-http-backend
spec:
  type: NodePort
  ports:
    - port: 8000
      nodePort: 30404 # this first node port will be bound to default catch all service automatically by nginx-lb service
  selector:
    app: default-http-backend
