#!/bin/bash
pushd $PWD > /dev/null
cd $(dirname $(realpath $0))/.k8s

OLD=$(cat deploy.yaml | sed -n -E -e 's/.*"VER_([0-9]+)"/\1/p')
NEW=$(($OLD + 1))
echo "============================="
echo "Start to deploy VER_$NEW"
eval "sed -i '' -e 's/VER_$OLD/VER_$NEW/' deploy.yaml"
docker build ../ -t gcr.io/benzen-179605/default-http-backend && gcloud docker -- push gcr.io/benzen-179605/default-http-backend && kubectl apply -f deploy.yaml

popd > /dev/null
